version: '2'
services:
    crud_mood-mongodb:
        container_name: crud_mood-mongodb
        image: mongo:3.3.9
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/crud_mood/mongodb/:/data/db/
